import pickle
import pprint

# 文件路径
file_path = '/home/madoka/python/rlbench_imitation_learning/training/pick_and_lift/30static_4_10000/config.pkl'

# 打开并读取 pickle 文件
with open(file_path, 'rb') as f:
    config = pickle.load(f)

# 使用 pprint 更清晰地打印配置内容
print("配置文件内容:")
pprint.pprint(config)


config_30static_4_4000_0 = {'actuator_config': {'actuator_network_dir': 'None',
                     'future_len': 'None',
                     'history_len': 'None',
                     'prediction_len': 'None'},
 'camera_names': ['front_camera',
                  'wrist_camera',
                  'overhead_camera',
                  'front_camera_mask',
                  'wrist_camera_mask',
                  'overhead_camera_mask'],
 'ckpt_dir': '/home/madoka/python/rlbench_imitation_learning/training/pick_and_lift/30static_4_4000_0',
 'episode_len': 250,
 'eval_every': 500,
 'load_pretrain': False,
 'lr': 1e-05,
 'num_steps': 10000,
 'onscreen_render': False,
 'policy_class': 'ACT',
 'policy_config': {'action_dim': 10,
                   'backbone': 'resnet18',
                   'camera_names': ['front_camera',
                                    'wrist_camera',
                                    'overhead_camera',
                                    'front_camera_mask',
                                    'wrist_camera_mask',
                                    'overhead_camera_mask'],
                   'ckpt_dir': '/home/madoka/python/rlbench_imitation_learning/training/pick_and_lift/30static_4_4000_0',
                   'dec_layers': 7,
                   'dim_feedforward': 3200,
                   'enc_layers': 4,
                   'hidden_dim': 512,
                   'kl_weight': 10,
                   'lr': 1e-05,
                   'lr_backbone': 1e-05,
                   'nheads': 8,
                   'no_encoder': False,
                   'num_queries': 100,
                   'num_steps': 10000,
                   'policy_class': 'ACT',
                   'seed': 0,
                   'task_name': 'pick_and_lift',
                   'vq': False,
                   'vq_class': 'None',
                   'vq_dim': 'None'},
 'real_robot': False,
 'resume_ckpt_path': False,
 'save_every': 500,
 'seed': 0,
 'state_dim': 8,
 'task_name': 'pick_and_lift',
 'temporal_agg': True,
 'validate_every': 500}

{'actuator_config': {'actuator_network_dir': 'None',
                     'future_len': 'None',
                     'history_len': 'None',
                     'prediction_len': 'None'},
 'camera_names': ['front_camera',
                  'wrist_camera',
                  'overhead_camera',
                  'front_camera_mask',
                  'wrist_camera_mask',
                  'overhead_camera_mask'],
 'ckpt_dir': '/home/madoka/python/rlbench_imitation_learning/training/pick_and_lift/30static_4_10000',
 'episode_len': 250,
 'eval_every': 500,
 'load_pretrain': False,
 'lr': 1e-05,
 'num_steps': 10000,
 'onscreen_render': False,
 'policy_class': 'ACT',
 'policy_config': {'action_dim': 10,
                   'backbone': 'resnet18',
                   'camera_names': ['front_camera',
                                    'wrist_camera',
                                    'overhead_camera',
                                    'front_camera_mask',
                                    'wrist_camera_mask',
                                    'overhead_camera_mask'],
                   'ckpt_dir': '/home/madoka/python/rlbench_imitation_learning/training/pick_and_lift/30static_4_10000',
                   'dec_layers': 7,
                   'dim_feedforward': 3200,
                   'enc_layers': 4,
                   'hidden_dim': 512,
                   'kl_weight': 10,
                   'lr': 1e-05,
                   'lr_backbone': 1e-05,
                   'nheads': 8,
                   'no_encoder': False,
                   'num_queries': 100,
                   'num_steps': 10000,
                   'policy_class': 'ACT',
                   'seed': 0,
                   'task_name': 'pick_and_lift',
                   'vq': False,
                   'vq_class': 'None',
                   'vq_dim': 'None'},
 'real_robot': False,
 'resume_ckpt_path': False,
 'save_every': 500,
 'seed': 0,
 'state_dim': 8,
 'task_name': 'pick_and_lift',
 'temporal_agg': True,
 'validate_every': 500}