defaults:
  - /default

task_name: pick_and_lift_norot
custom_task: attention_uni

policy:
  task_name: ${task_name}_${custom_task}
  camera_names:
    - front_camera_mask_attention_uni
    - wrist_camera_mask_attention_uni
    - overhead_camera_mask_attention_uni
  dataset_dir: data/${task_name}/${data_sampler_config.save_path_end}_hdf5
  ckpt_dir: training/${policy_class}_${task_name}/100demos_${custom_task}
  wandb_project_name: ${policy_class}_${task_name}_${custom_task}
  use_wandb: false
