defaults:
  - /default   

mode: ["collect_and_save_demos", "process_all_epochs", "*act_eval"]

data_sampler_config:
  headless: true
  cameras:
    # - 'front_camera'
    # - wrist_camera
    - overhead_camera

policy:
  ckpt_dir: training/${policy_class}_${task_name}/100demos_8_50_10000_o
  camera_names:
    # - front_camera
    # - wrist_camera
    - overhead_camera

 
