defaults:
  - /default   

policy_class: act_policy_smooth_attention

mode: ["collect_and_save_demos", "process_all_epochs", "*act_eval"]

data_sampler_config:
  headless: false
  cameras:
    - front_camera
    - wrist_camera
    - overhead_camera

policy:
  ckpt_dir: training/${policy_class}_${task_name}/100demos_8_50_10000_fwo
  camera_names:
    - front_camera
    - wrist_camera
    - overhead_camera
  batch_size: 8
  chunk_size: 50
  num_steps: 10000
  kl_weight: 1
  attn_smooth_weight: 0.1
