defaults:
  - /default   

mode: ["collect_and_save_demos", "process_all_epochs", "*act_eval"]

data_sampler_config:
  headless: true
  cameras:
    - wrist_camera


policy:
  ckpt_dir: training/${policy_class}_${task_name}/100demos_8_50_10000_w
  camera_names:
    - wrist_camera
  batch_size: 8
  chunk_size: 50
  num_steps: 10000
 
