defaults:
  - /default   

policy_class: act_weight_policy

policy:
  policy_class: ${policy_class}
  dataloader_name: act_dataloader
  model_name: act_model
  ckpt_dir: training/${policy_class}_${task_name}/100demos_bs4_s4000_test
  use_weight: true
  use_wandb: false
 