defaults:
  - /default   

mode: ["collect_and_save_demos", "process_all_epochs", "*act_eval"]

data_sampler_config:
  headless: false
  cameras:
    - front_camera
    - wrist_camera

policy:
  ckpt_dir: training/${policy_class}_${task_name}/100demos_8_50_10000_fw_mask
  camera_names:
    - front_camera_mask
    - wrist_camera_mask
  batch_size: 8
  chunk_size: 50
  num_steps: 10000