defaults:
  - /default   

policy_class: act_policy_smooth_attention
policy:
  ckpt_dir: training/${policy_class}_${task_name}_sweep_kl/${data_sampler_config.save_path_end}
  wandb_project_name: ${policy_class}_${task_name}_sweep_kl
  attn_smooth_weight: 1