#前面有*表示选择这个工具，逻辑上选择第一个带*的工具
tool_choice: ["formatconvert_raw2dp", "formatconvert_pngs2mp4", "*formatconvert_raw2act"]
formatconvert_raw2dp:
  src_path: "/home/starsky/project/imitation_learning/imitation_learning_ROS2/data/sample/demo1/2025-04-23-15-48-35/"
  output_path: "/home/starsky/project/imitation_learning/imitation_learning_ROS2/data/sample/demo1/2025-04-23-15-48-35_dp_data/" #千万别设置到src_path的子路径
  mp4_fps: 30
  show_output_data: False
  max_workers: 12
formatconvert_pngs2mp4:
  src_path: "/home/haoyue/code/imitation_learning/imitation_learning_ROS2/data/sample/test/"
  output_path: "/home/haoyue/code/imitation_learning/imitation_learning_ROS2/data/sample/grasp_redblock_record" #千万别设置到src_path的子路径
  mp4_fps: 30
  max_workers: 12
formatconvert_raw2act:
  # imitation_learning 相对路径
  src_path: "data/pick_and_lift/50demos"
  output_path: "act_plus/data/pick_and_lift/50demos"
